format = """
[](#FFAA00)\
$os\
$username\
[](bg:#7AA2F7 fg:#FFAA00)\
$directory\
[](fg:#7AA2F7 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#1A1B26)\
$fill\
$sudo\
$git_state\
$rust\
$python\
$battery\
\n$character"""

[os]
style = "bg:#FFAA00 fg:#000000"
disabled = false # Disabled by default
[os.symbols] # Overwrites for default icons
Macos = "  "
Windows = "  "
Ubuntu = "  "
Debian = "  "

[username]
show_always = false
style_user = "bg:#FFAA00 fg:#000000"
style_root = "bg:#FFAA00 fg:#000000"
format = '[ $user]($style)'
disabled = false

[directory]
style = "fg:#1A1B26 bg:#7AA2F7"
format = "[ $path ]($style)"
truncation_length = 4
truncation_symbol = "…/"
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
format = '[[ $symbol $branch ](fg:#7AA2F7 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#7AA2F7 bg:#394260)]($style)'

[fill]
symbol = ' '

[sudo]
disabled = false

[rust]
symbol = ""
style = "red bold"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "yellow bold"
format = '[ $symbol ($version) ]($style)'

[[battery.display]]
threshold = 50
style = 'bold red'

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '
