format = """
[](#FFAA00)\
$os\
$username\
[](bg:#769ff0 fg:#FFAA00)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$fill\
$sudo\
$git_state\
$rust\
$python\
$battery\
\n$character"""

[sudo]
disabled = false

[username]
show_always = false
style_user = "bg:#FFAA00 fg:#000000"
style_root = "bg:#FFAA00 fg:#000000"
format = '[ $user]($style)'
disabled = false

[os]
style = "bg:#FFAA00 fg:#000000"
disabled = false # Disabled by default
[os.symbols] # Overwrites for default icons
Macos = ""
Windows = ""

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 4
truncation_symbol = "…/"
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[[battery.display]]
threshold = 50
style = 'bold red'

[fill]
symbol = '.'

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

