format = """
[](orange)\
$os\
$username\
[](bg:light-blue fg:orange)\
$directory\
[](fg:light-blue bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:background)\
$fill\
$sudo\
$git_state\
$rust\
$custom\
$battery\
\n$character"""

palette = "tokyo-day"

[palettes.tokyo-dark]
background = "#1A1B26"
orange = "#FFAA00"
light-blue = "#7AA2F7"
grey-blue = "#3B4261"

[palettes.tokyo-day]
background = "#E1E2E7"
orange = "#FFAA00"
light-blue = "#7AA2F7"

[os]
style = "bg:orange fg:#000000"
disabled = false # Disabled by default
[os.symbols] # Overwrites for default icons
Macos = "  "
Windows = "  "
Ubuntu = "  "
Debian = "  "

[username]
show_always = false
style_user = "bg:#FFAA00 fg:#000000"
style_root = "bg:#FFAA00 fg:#000000"
format = '[ $user]($style)'
disabled = false

[directory]
style = "fg:#1A1B26 bg:light-blue"
format = "[ $path]($style)"
truncation_length = 4
truncation_symbol = "…/"
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
format = '[[ $symbol $branch ](fg:light-blue bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#7AA2F7 bg:#394260)]($style)'

[fill]
symbol = ' '

[sudo]
disabled = false

[rust]
symbol = ""
style = "red bold"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "yellow bold"
format = '[${symbol} (${version} )(\($virtualenv\) )]($style)'

[[battery.display]]
threshold = 50
style = 'bold red'

[character]
# success_symbol = '[➜](bold green) '
success_symbol = '[\$](bold green) '
error_symbol = '[✗](bold red) '

[custom.uv]
command = 'cat .python-version'
detect_files = ['uv.lock']
symbol = ' v'
style = 'bold yellow'
